### ISSUE TITLE
Production Use

### ISSUE THREAD

**Issue by rizplate** [adamcharnock/lightbus#3]
Is it ready for production? can we bet the farm on this :)

**Comment by adamcharnock** [comment]
Hello @rizplate, sorry for the delay in replying.

I'm currently using Lightbus in production, as is a colleague of mine. However, we are both very close to the project and so can tolerate breaking changes (I can warn him verbally) and missing documentation (he can ask me questions).

Moreover:

* Lightbus has also not seen a release yet
* I need to work on the documentation
* The API has not stabilised
* I would like to find additional contributors

That being said, Lightbus is well tested with good code coverage, and I plan to support this project for a long time to come.

I wouldn't however bet the farm on it just yet, certainly not for mission critical applications.

**Comment by adamcharnock** [comment]
Hi @rizplate,

I'm glad to hear you are interested! Lightbus is currently being used in production by myself and a colleague. We are both pretty close to the project though, so we can tolerate breaking changes and incomplete documentation (because I'm working on Lightbus myself and appreciate having a testing group, and because I can warn him of changes verbally).

Moreover:

* Lightbus has yet to have a release
* I'm still refining the API
* `aioredis` still needs to release streams support ([which is now in master](https://github.com/aio-libs/aioredis/pull/299))
* Redis 5 stable has not yet been release

It would certainly be very useful for me to get feedback from people making use of Lightbus, but I cannot in good faith say it is ready for mission-critical production deployment.

However, Lightbus is well tested and has proved to be reliable so far. I plan to maintain and support it for the foreseeable future. Given this, you may want to try it out for a non-critical deployment.

I'm planning to stabilise Lightbus over the coming months, once I'm happy with the API and code quality. At which point I'll to a `0.x` release.

Can I ask how you found Lightbus? Or what appeals to you about it?

**Comment by adamcharnock** [comment]
Hi @rizplate, I know you asked this over a year ago now, but on the off-chance that you are still looking: I performed the first release yesterday (`0.9.0`). Also Redis 5 has been stable for a while now, and `aioredis` has released its streams support. So everything should be good to go.
